[2021-12-11 16:05:07,405] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: dag_postgres_create_table.create_sample_table 2021-12-11T16:05:05.683743+00:00 [queued]>
[2021-12-11 16:05:07,423] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: dag_postgres_create_table.create_sample_table 2021-12-11T16:05:05.683743+00:00 [queued]>
[2021-12-11 16:05:07,424] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-12-11 16:05:07,424] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-12-11 16:05:07,425] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-12-11 16:05:07,434] {taskinstance.py:1107} INFO - Executing <Task(PostgresOperator): create_sample_table> on 2021-12-11T16:05:05.683743+00:00
[2021-12-11 16:05:07,439] {standard_task_runner.py:52} INFO - Started process 130 to run task
[2021-12-11 16:05:07,446] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_postgres_create_table', 'create_sample_table', '2021-12-11T16:05:05.683743+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres_create_table.py', '--cfg-path', '/tmp/tmp_lr7zzo4', '--error-file', '/tmp/tmpyzfjqosw']
[2021-12-11 16:05:07,449] {standard_task_runner.py:77} INFO - Job 2: Subtask create_sample_table
[2021-12-11 16:05:07,506] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_postgres_create_table.create_sample_table 2021-12-11T16:05:05.683743+00:00 [running]> on host a4b6b2594d54
[2021-12-11 16:05:07,556] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_postgres_create_table
AIRFLOW_CTX_TASK_ID=create_sample_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-11T16:05:05.683743+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-11T16:05:05.683743+00:00
[2021-12-11 16:05:07,558] {postgres.py:68} INFO - Executing: 
    DROP TABLE sample_table;

    CREATE TABLE sample_table
    (
        id integer,
        creation_date date,
        updated_date date,
        company_id integer,
        cash_in bigint,
        cash_out bigint
    );

    INSERT INTO sample_table VALUES (1, '2021-10-01', '2021-10-01', 234, 450, 455);
    INSERT INTO sample_table VALUES (2, '2021-11-01', '2021-11-01', 340, 40, 55);
    INSERT INTO sample_table VALUES (3, '2021-11-01', '2021-11-01', 340, 50, 55);
    INSERT INTO sample_table VALUES (4, '2021-11-01', '2021-11-03', 365, 1340, 3455);
    INSERT INTO sample_table VALUES (5, '2021-11-02', '2021-11-04', 365, 1200, 2455);
    INSERT INTO sample_table VALUES (6, '2021-11-04', '2021-11-04', 450, 0, 4);
    INSERT INTO sample_table VALUES (7, '2021-11-12', '2021-11-12', 450, 0, 55);
    INSERT INTO sample_table VALUES (8, '2021-11-15', '2021-11-20', 450, 0, 45);
    
[2021-12-11 16:05:07,569] {base.py:78} INFO - Using connection to: id: postgres_source. Host: postgres_source, Port: 5432, Schema: postgres, Login: admin, Password: ***, extra: {}
[2021-12-11 16:05:07,577] {dbapi.py:204} INFO - Running statement: 
    DROP TABLE sample_table;

    CREATE TABLE sample_table
    (
        id integer,
        creation_date date,
        updated_date date,
        company_id integer,
        cash_in bigint,
        cash_out bigint
    );

    INSERT INTO sample_table VALUES (1, '2021-10-01', '2021-10-01', 234, 450, 455);
    INSERT INTO sample_table VALUES (2, '2021-11-01', '2021-11-01', 340, 40, 55);
    INSERT INTO sample_table VALUES (3, '2021-11-01', '2021-11-01', 340, 50, 55);
    INSERT INTO sample_table VALUES (4, '2021-11-01', '2021-11-03', 365, 1340, 3455);
    INSERT INTO sample_table VALUES (5, '2021-11-02', '2021-11-04', 365, 1200, 2455);
    INSERT INTO sample_table VALUES (6, '2021-11-04', '2021-11-04', 450, 0, 4);
    INSERT INTO sample_table VALUES (7, '2021-11-12', '2021-11-12', 450, 0, 55);
    INSERT INTO sample_table VALUES (8, '2021-11-15', '2021-11-20', 450, 0, 45);
    , parameters: None
[2021-12-11 16:05:07,583] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 70, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: table "sample_table" does not exist

[2021-12-11 16:05:07,585] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=dag_postgres_create_table, task_id=create_sample_table, execution_date=20211211T160505, start_date=20211211T160507, end_date=20211211T160507
[2021-12-11 16:05:07,624] {local_task_job.py:149} INFO - Task exited with return code 1
